apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-tyedigital-mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql-dev-tyedigital
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-tyedigital-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-tyedigital-mysql
  labels:
    app: dev-tyedigital-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-tyedigital-mysql
  template:
    metadata:
      labels:
        app: dev-tyedigital-mysql
    spec:
      containers:
        - name: dev-tyedigital-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Kush@789#"
            - name: MYSQL_DATABASE
              value: "TYEDIGITAL"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: dev-tyedigital-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dev-tyedigital-mysql
spec:
  selector:
    app: dev-tyedigital-mysql
  type: NodePort
  ports:
    - nodePort: 31347
      port: 3306
      targetPort: 3306