package model

type (
	InputStruct struct {
		Id                        string `json:"id"`
		Lesson                    string `json:"lesson"`
		ProjectId                 string `json:"project_id"`
		ProjectName               string `json:"project_name"`
		ChapterId                 string `json:"chapter_id"`
		ProblemStatement          string `json:"problem_statement"`
		Deliverables              string `json:"deliverables"`
		ChapterName               string `json:"chapter_name"`
		RoleName                  string `json:"role_name"`
		SignatureBy               string `json:"signature_by"`
		SignatureLink             string `json:"signature_link"`
		TeamName                  string `json:"team_name"`
		UserID                    string `json:"user_id"`
		UserName                  string `json:"user_name"`
		RoleID                    string `json:"role_id"`
		Email                     string `json:"email"`
		SpentHours                string `json:"spent_hours"`
		Raised                    string `json:"raised"`
		UserTeamId                string `json:"user_team_id"`
		SignatureId               string `json:"signature_id"`
		CreatedBy                 string `json:"created_by"`
		LastUpdatedBy             string `json:"last_updated_by"`
		CreationDate              string `json:"creation_date"`
		LastUpdatedDate           string `json:"last_updated_date"`
		LinkedinUrl               string `json:"linkedin_url"`
		SocialMediaLink           string `json:"social_media_link"`
		PhotosUploaded            string `json:"photos_uploaded"`
		SchoolAttended            string `json:"school_attended"`
		BusinessIdeas             string `json:"business_ideas"`
		ImpactfulExperience       string `json:"impactful_experience"`
		FutureVision              string `json:"future_vision"`
		CurrentProjectInvolvement string `json:"current_project_involvement"`
		SuccessDefinition         string `json:"success_definition"`
		TyeExperienceImpact       string `json:"tye_experience_impact"`
		BiggestGoals              string `json:"biggest_goals"`
		MemorableExperienceTye    string `json:"memorable_experience_tye"`
		Hobbies                   string `json:"hobbies"`
		FavoriteSong              string `json:"favorite_song"`
		FavoriteMovie             string `json:"favorite_movie"`
		DesertedIslandItem        string `json:"deserted_island_item"`
		FavoriteFood              string `json:"favorite_food"`
		AdditionalComments        string `json:"additional_comments"`
		NewLearnedSkills          string `json:"new_learned_skills"`
		ProgramChallengesOvercome string `json:"program_challenges_overcome"`
		TeamRole                  string `json:"team_role"`
		VisitedCompanies          string `json:"visited_companies"`
		YourProduct               string `json:"your_product"`
		WeeklyProjectHours        string `json:"weekly_project_hours"`
		ProblemSolved             string `json:"problem_solved"`
		TyeBusinessName           string `json:"tye_business_name"`
		Country                   string `json:"country"`
		City                      string `json:"city"`
		FullAddress               string `json:"full_address"`
		ZipCode                   string `json:"zip_code"`
		Latidude                  string `json:"latidude"`
		Longitude                 string `json:"longitude"`
		LessonId                  string `json:"lesson_id"`
	}
)
